##### Script with graphs, tables and text for presentation in the urban observatory


suppressPackageStartupMessages(library(dplyr)) # for manipulating data
suppressPackageStartupMessages(library(tidyr))

source("./Scripts/scenarios_MEL.R")
source("./Scripts/graphs_AUO.R")

#### Results to be presented for: 
#1) Change mode share: see./scenarios/trips for all ages and sex. Code example below to generate for age and sex group
#2) Change mmets: see./scenarios/trips for all ages and sex. Code example below to generate for age and sex group
#3) diseases
#4) life expectancy
#5) life years

### Age groups: "15 to 19", "20 to 39", "40 to 64", "65 plus"
### Sex: "male", "female"

### Combinations age and sex for graphs and results
age_sex_cohorts <- crossing(data.frame(age=c("15 to 19", "20 to 39", "40 to 64", "65 plus")),
                            data.frame(sex=c('male', 'female'))) %>%
  dplyr::mutate(cohort=paste0(age,"_",sex))

# 1) Transport graph-example age group 20 to 39 and males

example_1_trips <- read.csv("./scenarios/trips/trips_all_0_2.csv")
example_1__trips_data <- example_1_trips %>% dplyr::filter(age_group=="20 to 39", sex == "female")

mode_example <- GraphsMode(example_1_trips_data)

mode_example 

#### 


# 2) TO DO:mmets graph-example age group 20 to 39 and males. Alan: METS are also generated by the CalculationModel functions,
# but are not part of the outputs that you shared with me. We need to present them. 
example_1_persons <- read.csv("./scenarios/persons/pop_matched_all_0_2.csv")
example_1_persons_data <- example_1_persons %>% dplyr::filter(age_group=="20 to 39", sex == "female")

example_1_mets <- GraphsmMETs(example_1_persons_data)


#3) diseases

### Table. Alan: 1) not sure why we have a variable scenario.x and sceanrio.y; and 2) We should consider adding up 
### the generation of results to match trip and mets age groups, too many age groups otherwise.
# Diseases names (for reference as tables use abbreviations)
# inc= Incidence
# mx =Deaths
## GUS: from here we want to present a table with age groups, sex, disease name (disease_names variable disease), median, 
## 2.5% and 97.5 % percentiles for diseases incidence (incident cases) and mx (deaths)
disaeses_names <- read.csv("./Data/processed/mslt/disease_names.csv")

diseases_all_scen <- read.csv("./scenarios/melbourne-outputs/output_diseases_change.csv")

diseases_all_example_scen <- dplyr::filter(diseases_all_scen, scenario.x == "all_0_2")

### Graph

#### Graphs for incidence, deaths and life years

data_example_sex <- read.csv("./scenarios/melbourne-outputs/output_df_agg_sex.csv")

data_example_all <- read.csv("./scenarios/melbourne-outputs/output_df_agg_all.csv")


### Incidence diseases (WE MAY WANT TO SMOOTH THE GRAPHS A BIT)
tmpPlot <- data_example_sex %>%
  filter(measure=="inc.num" & scenario.y== "diff" & scenario.x == "all_0_2") %>%
  arrange(Gender,measure,disease,year)
#& Gender=="female"
ggplot(tmpPlot, aes(x=year,y=median)) +
  geom_ribbon(aes(ymin=percentile025,ymax=percentile975),fill="grey75") +
  geom_line() +
  facet_grid(disease~Gender,scales="free") +
  scale_y_continuous(
    name = waiver(),
    breaks = waiver(),
    minor_breaks = NULL,
    n.breaks = 3,
    labels = waiver()) +
  labs(x="Simulation year", y="Incidence") +
  theme_bw()

### Mortality diseases
tmpPlot <- data_example_sex %>%
  filter(measure=="mx.num" & scenario.y== "diff" & scenario.x == "all_0_2") %>%
  arrange(Gender,measure,disease,year)
#& Gender=="female"
ggplot(tmpPlot, aes(x=year,y=median)) +
  geom_ribbon(aes(ymin=percentile025,ymax=percentile975),fill="grey75") +
  geom_line() +
  facet_grid(disease~Gender,scales="free") +
  scale_y_continuous(
    name = waiver(),
    breaks = waiver(),
    minor_breaks = NULL,
    n.breaks = 3,
    labels = waiver()) +
  labs(x="Simulation year", y="Mortality") +
  theme_bw()

### Heatlh adjusted life years
tmpPlot <- data_example_sex %>%
  filter(measure=="Lwx"  & scenario.y== "diff" & scenario.x == "all_0_2") %>%
  arrange(Gender,measure,disease,year)
#& Gender=="female"
ggplot(tmpPlot, aes(x=year,y=mean)) +
  geom_ribbon(aes(ymin=percentile025,ymax=percentile975),fill="grey75") +
  geom_line() +
  facet_grid(cols=vars(Gender),scales="free") +
  scale_y_continuous(
    name = waiver(),
    breaks = waiver(),
    minor_breaks = NULL,
    # n.breaks = 3,
    labels = waiver()) +
  labs(x="Simulation year", y="Health-adjusted life years") +
  theme_bw()
